"""Generate the bundled Conversations-page analyses (and the landing example).

Runs the real analysis pipeline over every demo conversation in
examples/conversations/ and writes each AnalysisResult as a static JSON the
frontend imports at build time, plus a typed index. conversation_0's result
also becomes frontend/src/exampleAnalysis.json — the landing-page example.

Two ways to get real judge output (no mocks — these are shipped as real
analyses):

    # 1. Local pipeline with your own key
    export ANTHROPIC_API_KEY=sk-ant-...
    python scripts/make_conversation_examples.py

    # 2. Reuse a deployed backend's key (nothing secret leaves your machine)
    python scripts/make_conversation_examples.py --api https://delaunay.onrender.com
"""
import argparse
import glob
import json
import os
import sys
import time
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
IN_DIR = REPO / "examples" / "conversations"
OUT_DIR = REPO / "frontend" / "src" / "conversations"
EXAMPLE_OUT = REPO / "frontend" / "src" / "exampleAnalysis.json"

INDEX_HEADER = """\
// GENERATED by scripts/make_conversation_examples.py — do not edit by hand.
// Pre-evaluated analyses of the demo conversations shown on the
// Conversations page. Regenerate after judge/prompt changes.
import type { AnalysisResult } from "../types";
"""


def _analyze_local(path: Path):
    sys.path.insert(0, str(REPO))
    from server.analysis.orchestrator import AnalysisOrchestrator
    from server.config_loader import load_config
    from server.parsing.transcript_parser import parse_transcript

    conv = parse_transcript(path.read_bytes(), path.name)
    orchestrator = AnalysisOrchestrator(load_config(str(REPO / "config.yaml")))
    result = orchestrator.analyze(conv)
    return json.loads(result.model_dump_json())


def _analyze_api(path: Path, base: str):
    import requests

    resp = requests.post(
        f"{base.rstrip('/')}/api/analyze",
        files={"file": (path.name, path.read_bytes(), "application/json")},
        timeout=300,
    )
    resp.raise_for_status()
    payload = resp.json()

    deadline = time.time() + 300
    while payload["status"] not in ("completed", "failed"):
        if time.time() > deadline:
            raise RuntimeError(f"{path.name}: analysis timed out")
        time.sleep(2)
        poll = requests.get(
            f"{base.rstrip('/')}/api/analysis/{payload['analysis_id']}", timeout=60,
        )
        poll.raise_for_status()
        payload = poll.json()
    if payload["status"] == "failed":
        raise RuntimeError(f"{path.name}: analysis failed: {payload.get('error')}")
    return payload["result"]


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--api", default=None,
                        help="base URL of a running backend to analyze through "
                             "(otherwise runs the local pipeline, which needs "
                             "ANTHROPIC_API_KEY)")
    args = parser.parse_args()

    if not args.api and not os.environ.get("ANTHROPIC_API_KEY"):
        print("error: set ANTHROPIC_API_KEY or pass --api <backend-url> — "
              "bundled analyses must come from the real judge", file=sys.stderr)
        sys.exit(2)

    sources = sorted(glob.glob(str(IN_DIR / "conversation_*.json")))
    if not sources:
        print(f"error: no conversations in {IN_DIR}", file=sys.stderr)
        sys.exit(2)

    OUT_DIR.mkdir(parents=True, exist_ok=True)
    entries = []
    for src in sources:
        src_path = Path(src)
        source = json.loads(src_path.read_text(encoding="utf-8"))
        title = (source.get("metadata") or {}).get("title") or source["conversation_id"]
        result = _analyze_api(src_path, args.api) if args.api else _analyze_local(src_path)
        if result["meta"].get("judge_error"):
            raise RuntimeError(
                f"{src_path.name}: judge unavailable ({result['meta']['warnings']}) — "
                "refusing to bundle an unjudged analysis"
            )
        out = OUT_DIR / f"{src_path.stem}.json"
        out.write_text(json.dumps(result, ensure_ascii=False, indent=2) + "\n",
                       encoding="utf-8")
        n_dets = sum(len(t["detections"]) for t in result["turns"])
        print(f"wrote {out.relative_to(REPO)} ({len(result['turns'])} turns, "
              f"{n_dets} detections, judge={result['meta']['judge_model']})")
        entries.append((src_path.stem, title))

    lines = [INDEX_HEADER]
    for stem, _title in entries:
        lines.append(f'import {stem} from "./{stem}.json";')
    lines.append("")
    lines.append("export interface ConversationExample {")
    lines.append("  id: string;")
    lines.append("  title: string;")
    lines.append("  analysis: AnalysisResult;")
    lines.append("}")
    lines.append("")
    lines.append("export const CONVERSATION_EXAMPLES: ConversationExample[] = [")
    for stem, title in entries:
        lines.append(f"  {{ id: {json.dumps(stem)}, title: {json.dumps(title)}, "
                     f"analysis: {stem} as unknown as AnalysisResult }},")
    lines.append("];")
    (OUT_DIR / "index.ts").write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"wrote {(OUT_DIR / 'index.ts').relative_to(REPO)} ({len(entries)} conversations)")

    # conversation_0 doubles as the landing-page example.
    first = OUT_DIR / "conversation_0.json"
    EXAMPLE_OUT.write_text(first.read_text(encoding="utf-8"), encoding="utf-8")
    print(f"wrote {EXAMPLE_OUT.relative_to(REPO)} (landing example = conversation_0)")


if __name__ == "__main__":
    main()
