// GENERATED by scripts/make_conversation_examples.py — do not edit by hand.
// Pre-evaluated analyses of the demo conversations shown on the
// Conversations page. Regenerate after judge/prompt changes.
import type { AnalysisResult } from "../types";

import conversation_0 from "./conversation_0.json";
import conversation_1 from "./conversation_1.json";
import conversation_2 from "./conversation_2.json";
import conversation_3 from "./conversation_3.json";
import conversation_4 from "./conversation_4.json";
import conversation_5 from "./conversation_5.json";
import conversation_6 from "./conversation_6.json";
import conversation_7 from "./conversation_7.json";

export interface ConversationExample {
  id: string;
  title: string;
  analysis: AnalysisResult;
}

export const CONVERSATION_EXAMPLES: ConversationExample[] = [
  { id: "conversation_0", title: "VS Code extension debugging", analysis: conversation_0 as unknown as AnalysisResult },
  { id: "conversation_1", title: "Taxes across two states", analysis: conversation_1 as unknown as AnalysisResult },
  { id: "conversation_2", title: "Presentation slide redesign", analysis: conversation_2 as unknown as AnalysisResult },
  { id: "conversation_3", title: "Competitor price scraping", analysis: conversation_3 as unknown as AnalysisResult },
  { id: "conversation_4", title: "Airline cancellation email", analysis: conversation_4 as unknown as AnalysisResult },
  { id: "conversation_5", title: "French Revolution essay", analysis: conversation_5 as unknown as AnalysisResult },
  { id: "conversation_6", title: "Climate model disagreement", analysis: conversation_6 as unknown as AnalysisResult },
  { id: "conversation_7", title: "Japanese translation", analysis: conversation_7 as unknown as AnalysisResult },
];
